language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: williamcaesar
  password: ${password}
  on:
    tags: true
    repo: williamcaesar/API_callers
    python: 3.6
